baseURL = "https://mto79.github.io/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "mto.nu"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX
publishDir = "mto79.github.io"

[Params]
  homeTitle = "Blog"
  subtitle = "Semper Exploro"
  mainSections = ["post","posts"]
  logo = "img/mto.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = false
  delayDisqus = true
  showRelatedPosts = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
# name = "Marc Ouwerkerk"
  website = "mto.nu"
  email = "marc@mto.nu"
  facebook = "marcouwerkerk"
  github = "mto79"
  twitter = "marc_ouwerkerk"
  linkedin = "marc-ouwerkerk-b085071b"
  instagram = "mto79"
  #youtube = "user/username" # or channel/channelname
  spotify = "21s6uhr6hwydu5gi53rdciyly"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 2
